{
  imports = [
    ./hyprland.nix
    ./home-manager.nix
    ./users/kyle.nix
    ./users/jon.nix
    ./users/george.nix
    ./users/luna.nix
    ./flakes.nix
    ./virtual-machines.nix
    ./hidpi.nix
    ./nvidia.nix
    ./greetd.nix
    ./bluetooth.nix
    ./hardware/intel.nix
    ./hardware/amd.nix
    ../../shared.nix
  ];
}
